
project:
  type: website

website:
  title: "SLR Suite"
  site-url: https://metinaktr.github.io/slr-suite/
  navbar:
    left:
      - text: "Makale"
        href: index.html

format:
  html:
    theme: cosmo
    toc: true
