source(file.path('R','thematic.R'),encoding='UTF-8')
df <- as.data.frame(readr::read_csv('data/interim/collection_screened.csv',show_col_types=FALSE))
if (!all(c('PY','ID') %in% names(df))) stop('Thematic evolution requires PY and ID fields.')
safe_breaks <- slr_thematic_breaks(df$PY)
message('>> Interior thematic cut years: ',paste(safe_breaks,collapse=', '))
# Real errors propagate to the orchestration log.
TE <- bibliometrix::thematicEvolution(df,field='ID',years=safe_breaks,n=250,minFreq=2)
if (!isTRUE(TE$check) || !nrow(TE$Nodes) || !nrow(TE$Edges)) stop('Thematic evolution produced no usable nodes or flows.')
OUT_DIR <- 'data/processed/thematic'
dir.create(OUT_DIR,recursive=TRUE,showWarnings=FALSE)
saveRDS(TE,file.path(OUT_DIR,'thematic_evolution.rds'))
readr::write_csv(TE$Nodes,file.path(OUT_DIR,'thematic_nodes.csv'))
readr::write_csv(TE$Edges,file.path(OUT_DIR,'thematic_edges.csv'))
source(file.path('R','thematic_static.R'),encoding='UTF-8')
slr_thematic_export(TE,file.path(OUT_DIR,'thematic_sankey'))
message('[OK] Thematic evolution and static PNG/SVG visualizations were generated.')
