name: Publish Quarto to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX (PDF için zorunlu)
        run: quarto install tinytex

      - name: Render Quarto site
        run: quarto render docs/paper

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/paper

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
